"""
app.py
------
Streamlit dashboard for the Budget-vs-Actual variance report.

All calculation logic lives in variance_engine.py / commentary.py; this
module only loads, filters, and renders. Nothing here recomputes a number
those modules already produce.

One design note worth being able to explain: revenue and expense are never
summed into a single headline figure. Adding a $50M revenue plan to a $62M
opex plan produces "$113M of budget", which represents nothing, and netting
a favourable revenue beat against an unfavourable cost overrun hides both.
The P&L view selector keeps the two separate.
"""

from pathlib import Path

import plotly.graph_objects as go
import streamlit as st

from commentary import add_commentary, fmt_money
from variance_engine import (
    DEFAULT_DATA_PATH,
    build_variance_report,
    flag_variances,
    load_data,
    summarize_by,
)

st.set_page_config(page_title="Budget vs Actual Variance Dashboard", layout="wide")


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data
def get_report():
    return build_variance_report(load_data(DEFAULT_DATA_PATH))


if not Path(DEFAULT_DATA_PATH).exists():
    st.error(
        f"Data file not found at `{DEFAULT_DATA_PATH}`. "
        "Run `generate_data.py` first to create it, e.g.:\n\n"
        '`& ".\\.venv\\Scripts\\python.exe" generate_data.py`'
    )
    st.stop()

report = get_report()

st.title("Budget vs Actual Variance Dashboard")
st.caption(
    "Automated monthly variance analysis with rule-based commentary. "
    "Data is synthetic and generated by `generate_data.py`."
)

# ---------------------------------------------------------------------------
# Sidebar filters
# ---------------------------------------------------------------------------
st.sidebar.header("Filters")

view = st.sidebar.radio(
    "P&L view",
    ["Operating expenses", "Revenue", "Both (detail only)"],
    index=0,
    help=(
        "Revenue and expense are reported separately. Summing them into one "
        "figure would be meaningless, so the KPI cards and trend chart follow "
        "this selection."
    ),
)
TYPE_MAP = {"Operating expenses": ["expense"], "Revenue": ["revenue"]}
selected_types = TYPE_MAP.get(view, ["revenue", "expense"])

departments = sorted(report["department"].unique())
accounts = sorted(
    report.loc[report["account_type"].isin(selected_types), "account"].unique()
)
months = sorted(report["month"].unique())

selected_departments = st.sidebar.multiselect(
    "Department", departments, default=departments
)
selected_accounts = st.sidebar.multiselect("Account", accounts, default=accounts)

month_start, month_end = st.sidebar.select_slider(
    "Month range", options=months, value=(months[0], months[-1])
)

pct_threshold_input = st.sidebar.slider(
    "Variance threshold (%)", min_value=5, max_value=25, value=10, step=1
)
dollar_floor = st.sidebar.number_input(
    "Dollar floor ($)", min_value=0, value=10_000, step=5_000
)
st.sidebar.caption(
    "An item must breach **both** the variance % threshold and the dollar "
    "floor to be flagged. Percentage alone over-flags small accounts; a "
    "dollar floor alone misses fast-growing small ones."
)

pct_threshold = pct_threshold_input / 100.0

# ---------------------------------------------------------------------------
# Apply filters
# ---------------------------------------------------------------------------
mask = (
    report["account_type"].isin(selected_types)
    & report["department"].isin(selected_departments)
    & report["account"].isin(selected_accounts)
    & (report["month"] >= month_start)
    & (report["month"] <= month_end)
)
filtered = report.loc[mask].copy()

if filtered.empty:
    st.warning("No data matches the current filters. Widen the selection to continue.")
    st.stop()

flagged = add_commentary(
    flag_variances(filtered, pct_threshold=pct_threshold, dollar_floor=dollar_floor),
    report,
)

# ---------------------------------------------------------------------------
# 1. KPI row
# ---------------------------------------------------------------------------
if view == "Both (detail only)":
    st.info(
        "Showing revenue and expense together. Headline totals are suppressed "
        "because summing revenue and cost produces a figure with no meaning — "
        "select a single view for KPIs and the trend chart."
    )
    kpi1, kpi2 = st.columns(2)
    kpi1.metric("Line items in view", f"{len(filtered):,}")
    kpi2.metric("Flagged items", f"{len(flagged):,}")
else:
    total_budget = filtered["budget"].sum()
    total_actual = filtered["actual"].sum()
    net_variance = total_actual - total_budget
    net_pct = net_variance / abs(total_budget) if total_budget else 0.0
    # Positive impact is always good for the P&L, whichever view is selected.
    net_impact = filtered["impact"].sum()

    label = "Revenue" if view == "Revenue" else "Opex"
    kpi1, kpi2, kpi3, kpi4 = st.columns(4)
    kpi1.metric(f"{label} Budget", fmt_money(total_budget))
    kpi2.metric(f"{label} Actual", fmt_money(total_actual))
    kpi3.metric(
        "Variance vs Budget",
        fmt_money(net_variance, signed=True),
        delta=f"{net_pct:+.1%} ({'favourable' if net_impact >= 0 else 'unfavourable'})",
        # Colour by P&L impact, not by raw sign: overspending is not "up".
        delta_color="normal" if net_impact >= 0 else "inverse",
    )
    kpi4.metric("Flagged Items", f"{len(flagged):,}")

st.divider()

# ---------------------------------------------------------------------------
# 2. Monthly budget-vs-actual trend
# ---------------------------------------------------------------------------
st.subheader(f"Monthly Budget vs Actual — {view}")

if view == "Both (detail only)":
    st.caption("Select 'Revenue' or 'Operating expenses' to view the trend.")
else:
    trend = summarize_by(filtered, "month").sort_values("month")
    fig_trend = go.Figure()
    fig_trend.add_trace(
        go.Scatter(x=trend["month"], y=trend["budget"], mode="lines+markers",
                   name="Budget", line=dict(dash="dash"))
    )
    fig_trend.add_trace(
        go.Scatter(x=trend["month"], y=trend["actual"], mode="lines+markers",
                   name="Actual")
    )
    fig_trend.update_layout(
        xaxis_title="Month", yaxis_title="Dollars",
        hovermode="x unified", margin=dict(t=20, b=20), height=380,
    )
    st.plotly_chart(fig_trend, width="stretch")

# ---------------------------------------------------------------------------
# 3. Variance by department (P&L impact)
# ---------------------------------------------------------------------------
st.subheader("P&L Impact by Department")
st.caption(
    "Positive = favourable to the P&L. Revenue above plan and spend below "
    "plan both count as favourable, which is why this uses signed impact "
    "rather than raw variance."
)

by_dept = (
    filtered.groupby("department", as_index=False)["impact"].sum()
    .sort_values("impact")
)
by_dept["color"] = by_dept["impact"].apply(
    lambda v: "#2ca02c" if v >= 0 else "#d62728"
)

fig_dept = go.Figure(
    go.Bar(
        x=by_dept["impact"], y=by_dept["department"], orientation="h",
        marker_color=by_dept["color"],
        text=[fmt_money(v, signed=True) for v in by_dept["impact"]],
        textposition="auto",
    )
)
fig_dept.update_layout(
    xaxis_title="P&L impact ($) — positive is favourable",
    yaxis_title="", margin=dict(t=20, b=20),
    height=90 + 45 * len(by_dept),
)
st.plotly_chart(fig_dept, width="stretch")

# ---------------------------------------------------------------------------
# 4. Flagged items table
# ---------------------------------------------------------------------------
st.subheader("Flagged Items")

if flagged.empty:
    st.info(
        "No items breach both thresholds under the current filters. "
        "Lower the variance threshold or the dollar floor to widen the net."
    )
else:
    pattern_counts = flagged["pattern"].value_counts()
    st.caption(" · ".join(f"**{k}**: {v}" for k, v in pattern_counts.items()))

    display_cols = [
        "month", "department", "account", "budget", "actual",
        "variance", "variance_pct", "severity", "pattern", "commentary",
    ]
    table = flagged.sort_values("impact")[display_cols].copy()

    shown = table.copy()
    for col in ("budget", "actual"):
        shown[col] = shown[col].apply(fmt_money)
    shown["variance"] = shown["variance"].apply(lambda v: fmt_money(v, signed=True))
    shown["variance_pct"] = shown["variance_pct"].apply(lambda v: f"{v:+.1%}")

    st.dataframe(
        shown,
        width="stretch",
        hide_index=True,
        column_config={
            "month": st.column_config.TextColumn("Month", width="small"),
            "variance_pct": st.column_config.TextColumn("Var %", width="small"),
            "commentary": st.column_config.TextColumn("Commentary", width="large"),
        },
    )

    # -----------------------------------------------------------------
    # 5. CSV export (raw, unformatted values so it opens clean in Excel)
    # -----------------------------------------------------------------
    st.download_button(
        "Download flagged items (CSV)",
        data=table.to_csv(index=False).encode("utf-8"),
        file_name="flagged_variances.csv",
        mime="text/csv",
    )